name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "5ca05847-e297-43f6-86e6-10ff0ec1b89a"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "2b2e91178b1642b3a63e14c0fa3c04a9"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
